---
Xres: 1920px
Yres: 1080px
SCALE: 150% #My PC likes to automatically turn on 150% scaling at 1920x1080.
#CHANGE yours if your screen is not scaled the same way! See Display settings -> Size and Layout
E: E
R: R
LMB: SHOT
RMB: PASS
W: UP
S: DOWN
A: LEFT
D: RIGHT
32: CAM #Space
Q: STEAL
Z: SWITCH
3: BOOST
4: BOOST_LOCK
F: BOOST
G: BOOST_LOCK
X: MV_CLICK
C: MV_BALL
I: INSTR
1: E
2: R
O: SHOT
P: PASS
#See link for key numbers in the left column
#https://docs.oracle.com/javase/7/docs/api/constant-values.html#java.awt.event.KeyEvent.VK_O
#Keys default to WASD Third-person-shooter style bindings