---
Xres: 1920px
Yres: 1080px
SCALE: 150%
theme: dark #light
rangewidth: 2px
shotwidth: 30px #So that the entire collision radius for the ball is shown
LMB: SHOT
RMB: MV_CLICK
32: CAM #Space
Q: E
W: R
E: STEAL
R: BOOST_LOCK
T: LOB
Z: SWITCH
1: E
2: R
3: BOOST
4: BOOST_LOCK
F: BOOST
G: BOOST_LOCK
X: MV_CLICK
C: MV_BALL
I: INSTR
O: SHOT
P: LOB
37: LEFT
38: UP
39: RIGHT
40: DOWN
#See link for key numbers in the left column
#https://docs.oracle.com/javase/7/docs/api/constant-values.html#java.awt.event.KeyEvent.VK_T
#Alternate RTS-style bindings provided with move-right-click for those used to games like LOL/DOTA