export const GamePhase = {
    CREDITS: 'CREDITS',
    CONTROLS: 'CONTROLS',
    SHOW_GAME_MODES: 'SHOW_GAME_MODES',
    DRAW_CLASS_SCREEN: 'DRAW_CLASS_SCREEN',
    SET_MASTERIES: 'SET_MASTERIES',
    TRANSITIONAL: 'TRANSITIONAL',
    WAIT_FOR_GAME: 'WAIT_FOR_GAME',
    CANNOT_JOIN: 'CANNOT_JOIN',
    COUNTDOWN: 'COUNTDOWN',
    INGAME: 'INGAME',
    SCORE_FREEZE: 'SCORE_FREEZE',
    TUTORIAL_START: 'TUTORIAL_START',
    TUTORIAL: 'TUTORIAL',
    ENDED: 'ENDED'
};

export const CONSTANTS = {
    X_RES: 1920,
    Y_RES: 960,
    DEFENSIVE_THIRD_X: 680,
    ATTACKING_THIRD_X: 1368
};